id: I878112C1
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T21:56:39.403682'
last_modified: '2022-05-30T21:56:39.403687'
parser: null
source_metadata:
  title: Kachöpa Series
  language: de
  description: Prayers and Practices
  volume:
    f24D2:
      title: Raising the Windhorse
      base_file: f24D2.txt
      order: 1
      parent: Prayers and Practices
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
